name: Artifacts

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [true, false]

    name: ${{ matrix.os }} ${{ matrix.python && 'w/' || 'w/o' }} Python
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Minimal Ubuntu Dependencies
      if: startsWith(matrix.os, 'ubuntu') && !matrix.python
      run: |
        sudo apt-get update
        sudo xargs apt-get -y install < dependencies-minimal.txt

    - name: Python Ubuntu Dependencies
      if: startsWith(matrix.os, 'ubuntu') && matrix.python
      run: |
        sudo apt-get update
        sudo xargs apt-get -y install < dependencies.txt

    - name: macOS Dependencies
      if: startsWith(matrix.os, 'macos')
      run: |
        brew update
        brew bundle -v
        brew install tree

    - name: Python macOS Dependency
      if: startsWith(matrix.os, 'macos') && matrix.python
      run: brew install python@3.11

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: |
        cmake -B${{github.workspace}}/build -S${{github.workspace}} -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE ${{ matrix.python && '-DPYTHON=yes' || '-DPYTHON=no' }}

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: File Tree
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: tree

    - name: Packing Artifact
      uses: actions/upload-artifact@v2
      with:
        name: far2l-release_${{ matrix.os }}_${{ matrix.python && 'python' || 'minimal' }}
        path: ${{github.workspace}}/build/install

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
